title : "Abdoul Aziz YARO"
logo :  "Yaro.Abdoul.Aziz/img/WhatsApp Image 2026-01-18 at 11.17.13.jpeg"
description :"Portfolio Analyste Statisticien"
show_downlead : true
theme : jekyll-theme-minimal
lann : fr
